---
title: "R Notebook"
output:
  html_document:
    df_print: paged
---

### Step 0 - Install and load all the required libraries

```{r load libraries, warning=FALSE, message=FALSE}
library(stringr)
library("syuzhet")
library(tidyr)
library(dplyr)
library(purrr)
library(ggplot2)
library(wordcloud)
library(memoise)
```

This notebook was prepared with the following environmental settings.

```{r}
print(R.version)
```
### Step 1 - Load the processed data

```{r}
# load processed lyrics data
# processed lyrics data was generated by "Text_Processing.Rmd"
load('../output/processed_lyrics.RData')
```

### Step 2 - Data analysis --- frequency of every word

```{r}
dt_rock = dt_lyrics%>% 
  dplyr::filter(genre == "Rock")
lyrics_rock = dt_rock %>% pull(stemmedwords) %>% paste(collapse = " ") %>% 
  strsplit(" ") %>% unlist()
words_rock = tibble(words = lyrics_rock) %>% 
  group_by(words) %>% count() %>%
  arrange(desc(n))

dt_hiphop = dt_lyrics %>% 
  dplyr::filter(genre == "Hip-Hop")
lyrics_hiphop = dt_hiphop %>% pull(stemmedwords) %>% paste(collapse = " ") %>% 
  strsplit(" ") %>% unlist()
words_hiphop = tibble(words = lyrics_hiphop) %>% 
  group_by(words) %>% count() %>%
  arrange(desc(n))
```

### Step 3 - Inspect an overall wordcloud

```{r, fig.height=6, fig.width=6}
wordcloud(words_rock$words, words_rock$n,
          scale=c(5,0.5),
          max.words=100,
          min.freq=1,
          random.order=FALSE,
          rot.per=0.3,
          use.r.layout=T,
          random.color=FALSE,
          colors=brewer.pal(9,"Blues"))

wordcloud(words_hiphop$words, words_hiphop$n,
          scale=c(5,0.5),
          max.words=100,
          min.freq=1,
          random.order=FALSE,
          rot.per=0.3,
          use.r.layout=T,
          random.color=FALSE,
          colors=brewer.pal(9,"Blues"))
```

### Step 5 - Data analysis --- sentiment analsis

```{r}
memoise(get_nrc_sentiment)
dt_rock_emo = dt_rock %>% 
  mutate(emotions=map(stemmedwords,get_nrc_sentiment)) %>% 
  unnest(emotions)
save(dt_rock_emo, file="../output/dt_rock_emotions.RData")

dt_hiphop_emo = dt_hiphop %>% 
  mutate(emotions=map(stemmedwords,get_nrc_sentiment)) %>% 
  unnest(emotions)
save(dt_hiphop_emo, file="../output/dt_hiphop_emotions.RData")


dt_rock_emo_plot = dt_rock_emo %>%  
  mutate(x = seq_along(id)) %>% 
  select(x, anger:trust) %>% 
  pivot_longer(anger:trust) %>% 
  group_by(x) %>% 
  top_n(1, value) %>% 
  mutate(color = map(name, ~switch (.x,
                                   anticipation = "green", 
                                   joy = "red", 
                                   surprise = "orange", 
                                   trust = "yellow", 
                                   anger = "black", 
                                   disgust = "grey", 
                                   fear = "blueviolet", 
                                   sadness = "blue"))
         ) %>% 
  unnest(color)

plot(dt_rock_emo_plot$x, dt_rock_emo_plot$value, 
     col = dt_rock_emo_plot$color, type="h", main = "Rock", xlab = "", ylab = "", xlim = c(1, 9000), ylim = c(0,30))

dt_hiphop_emo_plot = dt_hiphop_emo %>% 
  mutate(x = seq_along(id)) %>% 
  select(x, anger:trust) %>% 
  pivot_longer(anger:trust) %>% 
  group_by(x) %>% 
  top_n(1, value) %>% 
  mutate(color = map(name, ~switch (.x,
                                    anticipation = "green", 
                                    joy = "red", 
                                    surprise = "orange", 
                                    trust = "yellow", 
                                    anger = "black", 
                                    disgust = "grey", 
                                    fear = "blueviolet", 
                                    sadness = "blue"))
  ) %>% 
  unnest(color)

plot(dt_hiphop_emo_plot$x, dt_hiphop_emo_plot$value, 
     col = dt_hiphop_emo_plot$color, type="h")
```

### Step 6: Data analysis --- Topic modeling


